#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MaterialChipView.Resource", IsApplication=false)]

namespace MaterialChipView
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public static int alpha = 2130771968;
			
			// aapt resource value: 0x7F010001
			public static int font = 2130771969;
			
			// aapt resource value: 0x7F010002
			public static int fontProviderAuthority = 2130771970;
			
			// aapt resource value: 0x7F010003
			public static int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7F010004
			public static int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7F010005
			public static int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7F010006
			public static int fontProviderPackage = 2130771974;
			
			// aapt resource value: 0x7F010007
			public static int fontProviderQuery = 2130771975;
			
			// aapt resource value: 0x7F010008
			public static int fontStyle = 2130771976;
			
			// aapt resource value: 0x7F010009
			public static int fontVariationSettings = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public static int fontWeight = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public static int mcv_backgroundColor = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public static int mcv_chipIcon = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public static int mcv_chipText = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public static int mcv_closable = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public static int mcv_closeColor = 2130771983;
			
			// aapt resource value: 0x7F010010
			public static int mcv_cornerRadius = 2130771984;
			
			// aapt resource value: 0x7F010011
			public static int mcv_hasIcon = 2130771985;
			
			// aapt resource value: 0x7F010012
			public static int mcv_iconText = 2130771986;
			
			// aapt resource value: 0x7F010013
			public static int mcv_iconTextBackgroundColor = 2130771987;
			
			// aapt resource value: 0x7F010014
			public static int mcv_iconTextColor = 2130771988;
			
			// aapt resource value: 0x7F010015
			public static int mcv_selectable = 2130771989;
			
			// aapt resource value: 0x7F010016
			public static int mcv_selectedBackgroundColor = 2130771990;
			
			// aapt resource value: 0x7F010017
			public static int mcv_selectedCloseColor = 2130771991;
			
			// aapt resource value: 0x7F010018
			public static int mcv_selectedTextColor = 2130771992;
			
			// aapt resource value: 0x7F010019
			public static int mcv_strokeColor = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public static int mcv_strokeSize = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public static int mcv_textColor = 2130771995;
			
			// aapt resource value: 0x7F01001C
			public static int ttcIndex = 2130771996;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public static int colorChipBackground = 2130837504;
			
			// aapt resource value: 0x7F020001
			public static int colorChipBackgroundClicked = 2130837505;
			
			// aapt resource value: 0x7F020002
			public static int colorChipCloseClicked = 2130837506;
			
			// aapt resource value: 0x7F020003
			public static int colorChipCloseInactive = 2130837507;
			
			// aapt resource value: 0x7F020004
			public static int colorChipText = 2130837508;
			
			// aapt resource value: 0x7F020005
			public static int colorChipTextClicked = 2130837509;
			
			// aapt resource value: 0x7F020006
			public static int notification_action_color_filter = 2130837510;
			
			// aapt resource value: 0x7F020007
			public static int notification_icon_bg_color = 2130837511;
			
			// aapt resource value: 0x7F020008
			public static int ripple_material_light = 2130837512;
			
			// aapt resource value: 0x7F020009
			public static int secondary_text_default_material_light = 2130837513;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public static int chip_close_horizontal_margin = 2130903040;
			
			// aapt resource value: 0x7F030001
			public static int chip_close_icon_padding = 2130903041;
			
			// aapt resource value: 0x7F030002
			public static int chip_close_icon_size = 2130903042;
			
			// aapt resource value: 0x7F030003
			public static int chip_close_icon_size2 = 2130903043;
			
			// aapt resource value: 0x7F030004
			public static int chip_height = 2130903044;
			
			// aapt resource value: 0x7F030005
			public static int chip_horizontal_padding = 2130903045;
			
			// aapt resource value: 0x7F030006
			public static int chip_icon_horizontal_margin = 2130903046;
			
			// aapt resource value: 0x7F030007
			public static int compat_button_inset_horizontal_material = 2130903047;
			
			// aapt resource value: 0x7F030008
			public static int compat_button_inset_vertical_material = 2130903048;
			
			// aapt resource value: 0x7F030009
			public static int compat_button_padding_horizontal_material = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public static int compat_button_padding_vertical_material = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public static int compat_control_corner_material = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public static int compat_notification_large_icon_max_height = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public static int compat_notification_large_icon_max_width = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public static int notification_action_icon_size = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public static int notification_action_text_size = 2130903055;
			
			// aapt resource value: 0x7F030010
			public static int notification_big_circle_margin = 2130903056;
			
			// aapt resource value: 0x7F030011
			public static int notification_content_margin_start = 2130903057;
			
			// aapt resource value: 0x7F030012
			public static int notification_large_icon_height = 2130903058;
			
			// aapt resource value: 0x7F030013
			public static int notification_large_icon_width = 2130903059;
			
			// aapt resource value: 0x7F030014
			public static int notification_main_column_padding_top = 2130903060;
			
			// aapt resource value: 0x7F030015
			public static int notification_media_narrow_margin = 2130903061;
			
			// aapt resource value: 0x7F030016
			public static int notification_right_icon_size = 2130903062;
			
			// aapt resource value: 0x7F030017
			public static int notification_right_side_padding_top = 2130903063;
			
			// aapt resource value: 0x7F030018
			public static int notification_small_icon_background_padding = 2130903064;
			
			// aapt resource value: 0x7F030019
			public static int notification_small_icon_size_as_large = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public static int notification_subtext_size = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public static int notification_top_pad = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public static int notification_top_pad_large_text = 2130903068;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public static int ic_close = 2130968576;
			
			// aapt resource value: 0x7F040001
			public static int ic_select = 2130968577;
			
			// aapt resource value: 0x7F040002
			public static int notification_action_background = 2130968578;
			
			// aapt resource value: 0x7F040003
			public static int notification_bg = 2130968579;
			
			// aapt resource value: 0x7F040004
			public static int notification_bg_low = 2130968580;
			
			// aapt resource value: 0x7F040005
			public static int notification_bg_low_normal = 2130968581;
			
			// aapt resource value: 0x7F040006
			public static int notification_bg_low_pressed = 2130968582;
			
			// aapt resource value: 0x7F040007
			public static int notification_bg_normal = 2130968583;
			
			// aapt resource value: 0x7F040008
			public static int notification_bg_normal_pressed = 2130968584;
			
			// aapt resource value: 0x7F040009
			public static int notification_icon_background = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public static int notification_template_icon_bg = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public static int notification_template_icon_low_bg = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public static int notification_tile_bg = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public static int notify_panel_notification_icon_bg = 2130968589;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050004
			public static int actions = 2131034116;
			
			// aapt resource value: 0x7F050000
			public static int action_container = 2131034112;
			
			// aapt resource value: 0x7F050001
			public static int action_divider = 2131034113;
			
			// aapt resource value: 0x7F050002
			public static int action_image = 2131034114;
			
			// aapt resource value: 0x7F050003
			public static int action_text = 2131034115;
			
			// aapt resource value: 0x7F050005
			public static int async = 2131034117;
			
			// aapt resource value: 0x7F050006
			public static int blocking = 2131034118;
			
			// aapt resource value: 0x7F050007
			public static int chip_image = 2131034119;
			
			// aapt resource value: 0x7F050008
			public static int chip_text = 2131034120;
			
			// aapt resource value: 0x7F050009
			public static int chronometer = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public static int forever = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public static int icon = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public static int icon_group = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public static int info = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public static int italic = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public static int line1 = 2131034127;
			
			// aapt resource value: 0x7F050010
			public static int line3 = 2131034128;
			
			// aapt resource value: 0x7F050011
			public static int normal = 2131034129;
			
			// aapt resource value: 0x7F050012
			public static int notification_background = 2131034130;
			
			// aapt resource value: 0x7F050013
			public static int notification_main_column = 2131034131;
			
			// aapt resource value: 0x7F050014
			public static int notification_main_column_container = 2131034132;
			
			// aapt resource value: 0x7F050015
			public static int right_icon = 2131034133;
			
			// aapt resource value: 0x7F050016
			public static int right_side = 2131034134;
			
			// aapt resource value: 0x7F050017
			public static int tag_transition_group = 2131034135;
			
			// aapt resource value: 0x7F050018
			public static int tag_unhandled_key_event_manager = 2131034136;
			
			// aapt resource value: 0x7F050019
			public static int tag_unhandled_key_listeners = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public static int text = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public static int text2 = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public static int time = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public static int title = 2131034141;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F060000
			public static int status_bar_notification_info_maxnum = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F070000
			public static int notification_action = 2131165184;
			
			// aapt resource value: 0x7F070001
			public static int notification_action_tombstone = 2131165185;
			
			// aapt resource value: 0x7F070002
			public static int notification_template_custom_big = 2131165186;
			
			// aapt resource value: 0x7F070003
			public static int notification_template_icon_group = 2131165187;
			
			// aapt resource value: 0x7F070004
			public static int notification_template_part_chronometer = 2131165188;
			
			// aapt resource value: 0x7F070005
			public static int notification_template_part_time = 2131165189;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public static int status_bar_notification_info_overflow = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public static int TextAppearance_Compat_Notification = 2131296256;
			
			// aapt resource value: 0x7F090001
			public static int TextAppearance_Compat_Notification_Info = 2131296257;
			
			// aapt resource value: 0x7F090002
			public static int TextAppearance_Compat_Notification_Line2 = 2131296258;
			
			// aapt resource value: 0x7F090003
			public static int TextAppearance_Compat_Notification_Time = 2131296259;
			
			// aapt resource value: 0x7F090004
			public static int TextAppearance_Compat_Notification_Title = 2131296260;
			
			// aapt resource value: 0x7F090005
			public static int Widget_Compat_NotificationActionContainer = 2131296261;
			
			// aapt resource value: 0x7F090006
			public static int Widget_Compat_NotificationActionText = 2131296262;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F01000B,0x7F01000C,0x7F01000D,0x7F01000E,0x7F01000F,0x7F010010,0x7F010011,0x7F010012,0x7F010013,0x7F010014,0x7F010015,0x7F010016,0x7F010017,0x7F010018,0x7F010019,0x7F01001A,0x7F01001B }
			public static int[] Chip = new int[] {
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995};
			
			// aapt resource value: 0
			public static int Chip_mcv_backgroundColor = 0;
			
			// aapt resource value: 1
			public static int Chip_mcv_chipIcon = 1;
			
			// aapt resource value: 2
			public static int Chip_mcv_chipText = 2;
			
			// aapt resource value: 3
			public static int Chip_mcv_closable = 3;
			
			// aapt resource value: 4
			public static int Chip_mcv_closeColor = 4;
			
			// aapt resource value: 5
			public static int Chip_mcv_cornerRadius = 5;
			
			// aapt resource value: 6
			public static int Chip_mcv_hasIcon = 6;
			
			// aapt resource value: 7
			public static int Chip_mcv_iconText = 7;
			
			// aapt resource value: 8
			public static int Chip_mcv_iconTextBackgroundColor = 8;
			
			// aapt resource value: 9
			public static int Chip_mcv_iconTextColor = 9;
			
			// aapt resource value: 10
			public static int Chip_mcv_selectable = 10;
			
			// aapt resource value: 11
			public static int Chip_mcv_selectedBackgroundColor = 11;
			
			// aapt resource value: 12
			public static int Chip_mcv_selectedCloseColor = 12;
			
			// aapt resource value: 13
			public static int Chip_mcv_selectedTextColor = 13;
			
			// aapt resource value: 14
			public static int Chip_mcv_strokeColor = 14;
			
			// aapt resource value: 15
			public static int Chip_mcv_strokeSize = 15;
			
			// aapt resource value: 16
			public static int Chip_mcv_textColor = 16;
			
			// aapt resource value: { 0x10101A5,0x101031F,0x7F010000 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771968};
			
			// aapt resource value: 2
			public static int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public static int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public static int ColorStateListItem_android_color = 0;
			
			// aapt resource value: { 0x7F010002,0x7F010003,0x7F010004,0x7F010005,0x7F010006,0x7F010007 }
			public static int[] FontFamily = new int[] {
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F010001,0x7F010008,0x7F010009,0x7F01000A,0x7F01001C }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771969,
					2130771976,
					2130771977,
					2130771978,
					2130771996};
			
			// aapt resource value: 0
			public static int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public static int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public static int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public static int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public static int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public static int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public static int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public static int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public static int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public static int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public static int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public static int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public static int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public static int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public static int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public static int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public static int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public static int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public static int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public static int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public static int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public static int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public static int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public static int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public static int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public static int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public static int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public static int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public static int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public static int GradientColor_android_type = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
