#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MaterialChipView.Resource", IsApplication=false)]

namespace MaterialChipView
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public static int mcv_backgroundColor = 2130771968;
			
			// aapt resource value: 0x7F010001
			public static int mcv_chipIcon = 2130771969;
			
			// aapt resource value: 0x7F010002
			public static int mcv_chipText = 2130771970;
			
			// aapt resource value: 0x7F010003
			public static int mcv_closable = 2130771971;
			
			// aapt resource value: 0x7F010004
			public static int mcv_closeColor = 2130771972;
			
			// aapt resource value: 0x7F010005
			public static int mcv_cornerRadius = 2130771973;
			
			// aapt resource value: 0x7F010006
			public static int mcv_hasIcon = 2130771974;
			
			// aapt resource value: 0x7F010007
			public static int mcv_iconText = 2130771975;
			
			// aapt resource value: 0x7F010008
			public static int mcv_iconTextBackgroundColor = 2130771976;
			
			// aapt resource value: 0x7F010009
			public static int mcv_iconTextColor = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public static int mcv_selectable = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public static int mcv_selectedBackgroundColor = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public static int mcv_selectedCloseColor = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public static int mcv_selectedTextColor = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public static int mcv_strokeColor = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public static int mcv_strokeSize = 2130771983;
			
			// aapt resource value: 0x7F010010
			public static int mcv_textColor = 2130771984;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public static int colorChipBackground = 2130837504;
			
			// aapt resource value: 0x7F020001
			public static int colorChipBackgroundClicked = 2130837505;
			
			// aapt resource value: 0x7F020002
			public static int colorChipCloseClicked = 2130837506;
			
			// aapt resource value: 0x7F020003
			public static int colorChipCloseInactive = 2130837507;
			
			// aapt resource value: 0x7F020004
			public static int colorChipText = 2130837508;
			
			// aapt resource value: 0x7F020005
			public static int colorChipTextClicked = 2130837509;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public static int chip_close_horizontal_margin = 2130903040;
			
			// aapt resource value: 0x7F030001
			public static int chip_close_icon_padding = 2130903041;
			
			// aapt resource value: 0x7F030002
			public static int chip_close_icon_size = 2130903042;
			
			// aapt resource value: 0x7F030003
			public static int chip_close_icon_size2 = 2130903043;
			
			// aapt resource value: 0x7F030004
			public static int chip_height = 2130903044;
			
			// aapt resource value: 0x7F030005
			public static int chip_horizontal_padding = 2130903045;
			
			// aapt resource value: 0x7F030006
			public static int chip_icon_horizontal_margin = 2130903046;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public static int ic_close = 2130968576;
			
			// aapt resource value: 0x7F040001
			public static int ic_select = 2130968577;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public static int chip_image = 2131034112;
			
			// aapt resource value: 0x7F050001
			public static int chip_text = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010000,0x7F010001,0x7F010002,0x7F010003,0x7F010004,0x7F010005,0x7F010006,0x7F010007,0x7F010008,0x7F010009,0x7F01000A,0x7F01000B,0x7F01000C,0x7F01000D,0x7F01000E,0x7F01000F,0x7F010010 }
			public static int[] Chip = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 0
			public static int Chip_mcv_backgroundColor = 0;
			
			// aapt resource value: 1
			public static int Chip_mcv_chipIcon = 1;
			
			// aapt resource value: 2
			public static int Chip_mcv_chipText = 2;
			
			// aapt resource value: 3
			public static int Chip_mcv_closable = 3;
			
			// aapt resource value: 4
			public static int Chip_mcv_closeColor = 4;
			
			// aapt resource value: 5
			public static int Chip_mcv_cornerRadius = 5;
			
			// aapt resource value: 6
			public static int Chip_mcv_hasIcon = 6;
			
			// aapt resource value: 7
			public static int Chip_mcv_iconText = 7;
			
			// aapt resource value: 8
			public static int Chip_mcv_iconTextBackgroundColor = 8;
			
			// aapt resource value: 9
			public static int Chip_mcv_iconTextColor = 9;
			
			// aapt resource value: 10
			public static int Chip_mcv_selectable = 10;
			
			// aapt resource value: 11
			public static int Chip_mcv_selectedBackgroundColor = 11;
			
			// aapt resource value: 12
			public static int Chip_mcv_selectedCloseColor = 12;
			
			// aapt resource value: 13
			public static int Chip_mcv_selectedTextColor = 13;
			
			// aapt resource value: 14
			public static int Chip_mcv_strokeColor = 14;
			
			// aapt resource value: 15
			public static int Chip_mcv_strokeSize = 15;
			
			// aapt resource value: 16
			public static int Chip_mcv_textColor = 16;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
